- R/get_eval_details.R
Update font awesome icon labels for FA 6, to avoid warnings like:
```
This Font Awesome icon ('some icon') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
be deactivated with `verify_fa = FALSE`
```
> Update font awesome icon labels for FA 6

- R/qenv-constructor.R
- R/qenv-join.R
- man/new_qenv.Rd
- tests/testthat/test-qenv_constructor.R
- tests/testthat/test-qenv_join.R
Closes #69 and also removes the option to create `qenv` with list and attr(code) as this is not needed anymore
> Improve error message

- R/qenv-get_var.R
- tests/testthat/test-qenv_get_var.R
closes #57 
Returns `NULL` when variable not found in `qenv` or with `qenv-error` when calling `get_var` or `[[var]]`.
> qenv: return NULL when var not found

- DESCRIPTION
- R/qenv-eval_code.R
Closes #86 
```
library(teal.code)
library(shiny)
library(dplyr)
library(teal.widgets)
ui <- fluidPage(
plotOutput("plot"),
verbatim_popup_ui("src", "SRC")
)
server <- function(input, output, session) {
q1 <- reactive({
new_qenv() %>%
eval_code(quote(x <- dplyr::select(iris, f))) %>%
eval_code(quote(p <- hist(iris[, "Species"])))
})
output$plot <- renderPlot(q1()[["p"]])
verbatim_popup_srv("src", reactive(paste(teal.code::get_code(q1()), collapse = "\n")), title = "SRC")
}
shinyApp(ui, server)
```
> strip rlang error symbols

- R/qenv-join.R
- man/dot-check_joinable.Rd
- man/join.Rd
closes #71 
move docs from check_joinable to join methods and improve documentation.
> improve join docs

- R/chunks.R
- R/get_eval_details.R
The next release version will be 0.3.0.
Updating the value of `deprecate_warn(where=)` in chunks feature.
> update the value of `deprecate_warn(where=)`

- README.md
- inst/WORDLIST
The follow-up after https://github.com/insightsengineering/coredev-tasks/issues/235
Not much to clean in this case.
Output of `spelling::spell_check_package()` is short
```{R}
WORD              FOUND IN
Forkers           README.md:48,58,60
funder            teal.code-package.Rd:28
Github            README.md:35
Hoffmann          teal.code-package.Rd:28
repo              README.md:9,15,56,60
reproducibility   README.md:27
qenv.Rmd:32
teal-code.Rmd:24
Reproducibility   teal-code.Rmd:2,13
UI                get_eval_details_srv.Rd:11
```
> reduce the amount of spelling issues / WORDLIST

- DESCRIPTION
- NEWS.md
- R/utils.R
- README.md
- man/dev_suppress.Rd
- man/teal.code-package.Rd
Related to #132 
Pushing to CRAN
* Up-version the package (0.4.1) + update PR title to skip vbump.
* Built this locally and submit to CRAN
* git tag v0.4.1-rc# and push
* Address any CRAN feedback and repeat steps 2 and 3 until CRAN approves.
* Once in CRAN, then we will merge this to main and tag v0.4.1 for GH release
> CRAN Release [skip vbump]

- R/qenv-eval_code.R
- tests/testthat/test-qenv_eval_code.R
Possible to include `library` call in `eval_code`
https://github.com/insightsengineering/teal.code/issues/93
> library calls possible within a call

- _pkgdown.yml
> remove replace_code from pkgdown

- NAMESPACE
- NEWS.md
- R/qenv-within.R
- tests/testthat/test-qenv-within.R
Closes #180 
Added method `within.qenv.error` that returns the `qenv.error` as is.
> 180 missing method `within.qenv.error`

- R/qenv-get_var.R
- tests/testthat/test-qenv_get_var.R
Closes #94 
Added `inherits = FALSE` to `get` call in `get_var`.
Added unit tests.
> 94 `get_var` `inherits = FALSE`

- R/qenv-join.R
- R/utils.R
- man/dev_suppress.Rd
- man/join.Rd
this is part of https://github.com/insightsengineering/teal.code/pull/189
I noticed some old syntax that was not previously checked, so I am creating a separate pull request for it.
> Removing old rd syntax

- DESCRIPTION
- NEWS.md
- R/qenv-constructor.R
> [skip vbump] CRAN Release v0.5.0

- DESCRIPTION
- tests/testthat/setup-options.R
- part of https://github.com/insightsengineering/coredev-tasks/issues/478
- please read this for more info about the implementation: https://github.com/insightsengineering/coredev-tasks/issues/478#issuecomment-1909912778
Please review the changes carefully and let me know if there is something you don't like.
> options for strict tests

- DESCRIPTION
- vignettes/qenv.Rmd
Fixes #206 
Nosuggest pipeline passed:
https://github.com/insightsengineering/teal.code/actions/runs/10517334132/job/29141241618
> 206 fix failed pipeline

- DESCRIPTION
Fixes #219 
We need to bump up `testthat` version because we're using `testthat::it` function in unit tests.
This function was introduced in `3.1.8`:
https://github.com/r-lib/testthat/blob/v3.1.8/R/describe.R#L89
> update testthat version

- R/qenv-class.R
- R/qenv-eval_code.R
- R/utils-get_code_dependency.R
- man/qenv-class.Rd
- tests/testthat/test-qenv_eval_code.R
- tests/testthat/test-qenv_get_code.R
> assign `side_effects` and `occurrence` as attributes of `@code`

- R/qenv-eval_code.R
- man/qenv.Rd
- tests/testthat/test-qenv_eval_code.R
- tests/testthat/test-qenv_within.R
> Fixes integer shorthand regression

- .github/workflows/check.yaml
- .github/workflows/docs.yaml
- .github/workflows/release.yaml
Related to https://github.com/insightsengineering/nestdevs-tasks/issues/65
Switch to setup-r-dependencies.
A straightforward update as we don't need `lookup-refs`.
> add setup-r-dependencies

- DESCRIPTION
- NEWS.md
- R/qenv-get_var.R
- R/qenv-join.R
Fixes #240 
* Update NEWS
* I'm reverting the NEWS.md update in this commit d2d17477590fb5d88ebd0bf65471bdaf2e2ffcc9 and make a new entry under 0.6.0 noting that function is now removed from the package.
* Update DESCRIPTION
* Change the deprecated message to version `0.6.0`
> [skip vbump] upversion to 0.6.0

- NEWS.md
- R/utils-get_code_dependency.R
- tests/testthat/test-qenv_get_code.R
closes https://github.com/insightsengineering/teal/issues/1474
Problem happens when two or more symbols occur in the same time on rhs and lhs. Due to this, `l` depends on `class` and `class` depends on `l`.
```r
code <- "l <- list(a = 1, b = 2)
class(l) <- c('new class', class(l))" # l depends on class and class depends on l
q <- eval_code(qenv(), code)
get_code(q, names = "l")
```
@donyunardi This was a serious bug and will require a new release. We can wait a little to the day when `teal` is going to be submitted to CRAN.
> Fix infinite loop

- R/qenv-eval_code.R
- tests/testthat/test-qenv_within.R
- Fixes #252
- Adds special case for `=` as it is not recognizes as `language` in S4 dispatch
the code with `=` call has a language type, but it tales priority somewhere on the dispatcher and tries to dispatch with this class (`->` doesn't have a problem)
> Creates special case for '=' processing

- NEWS.md
- R/utils-get_code_dependency.R
- teal.code.Rproj
- tests/testthat/test-utils-get_code_dependency.R
Fixes #249
- Detects expression blocks and handles them one by one
- Any co-occurence is tracked to the single line
> Fixes bug in execution with multiple assignments inside expression

- R/utils-get_code_dependency.R
- tests/testthat/test-qenv_constructor.R
- tests/testthat/test-qenv_eval_code.R
- tests/testthat/test-qenv_get_code.R
> Fix tests in `use_evaluate` branch

- R/qenv-eval_code.R
- tests/testthat/test-get_outputs.R
- tests/testthat/test-qenv_eval_code.R
- Remove intermediate plots by default
- Avoids deprecated function in testthat 3rd edition
- Adds some tests
- Q: Does the S4 test make sense?
> Adds some tests to `use_evaluate` feature branch and avoids deprecated function
